import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import Navbar from '@/components/Navbar/Navbar';

// const geistSans = GeistSans();
// const geistMono = GeistMono();

export const metadata = {
  title: 'GDSC NIT Calicut',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${GeistSans.variable} ${GeistMono.variable}`}>
      <body>
        <div className="max-w-[110rem] mx-auto">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
